Update checkupg

diff --git a/resources/checkupg b/resources/checkupg
--- a/resources/checkupg
+++ b/resources/checkupg
@@ -12,7 +12,7 @@ getConfiguredClient()
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: Necesitas curl, wget, httpie o fetch instalado\." >&2
+    echo "Error: You need curl, wget, httpie o fetch installed\." >&2
     return 1
   fi
 }
@@ -29,7 +29,7 @@ httpGet()
 
 checkInternet()
 {
-  httpGet google.com > /dev/null 2>&1 || { echo "Error: No hay conexion a internet" >&2; return 1; } # query google with a get request
+  httpGet google.com > /dev/null 2>&1 || { echo "Error: There isn't Internet conection" >&2; return 1; }
 }
 
 getConfiguredClient || exit 1
@@ -38,7 +38,7 @@ checkInternet || exit 1
 UltimaVersion=$(httpGet https://api.github.com/repos/SrWither/VsVim/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" )
 
 if [[ "$UltimaVersion" != "$VersionActual" ]]; then
-	echo "VsVim '$UltimaVersion' Disponible, Actualizalo con 'vsvupg'"
-	# ~/.local/bin/vsvupg # Actualizar neovim al abrir la terminal
+	echo "VsVim '$UltimaVersion' available, Update with 'vsvupg'"
+	# ~/.local/bin/vsvupg # Update neovim when opening terminal
 fi
 
